"""Live integration tests for PlanEvent formatting with realistic decomposer data.

These tests use real-world task text patterns (long multi-paragraph agent prompts
as actually generated by the decomposer router) to validate that format_event
produces a usable Telegram notification even when task text is verbose.
"""

import html

import pytest

from archon.ai.agent_plan import AgentPlan, AgentTask
from archon.ai.event_mapper import PlanEvent
from archon.ai.truncation import SplitStrategy
from archon.chat.handler import format_event, _task_summary
from archon.config.loader import NotificationsConfig


_split = SplitStrategy()

# ── Real-world task text patterns extracted from ~/.archon/history/sessions/ ──

_REAL_TASK_RESEARCH = (
    "You are a web research agent. Your job is to find where to buy the "
    "Nike Zoom Mercurial Superfly 10 Academy FG/MG football boots in EU size 39 "
    "in Hungary online.\n\nThe reference product page is: "
    "https://www.r-gol.com/hu/nike-zoom-mercurial-superfly-10-academy-fg-mg,p-200792\n\n"
    "Research the following Hungarian online stores for this exact product in EU 39:\n"
    "1. r-gol.com — check if they have EU 39 in stock\n"
    "2. nike.com/hu — check the official Nike Hungary store\n"
    "3. intersport.hu — search for this model in EU 39\n"
    "4. hervis.hu — search for this model in EU 39\n\n"
    "For each store, report:\n"
    "- Whether the product is available in EU 39\n"
    "- Current price in HUF\n"
    "- Direct URL to the product page"
)

_REAL_TASK_IMPLEMENT = (
    "You are an implementation agent working in the Archon project at "
    "/Users/manczg/Documents/development/archon.\n\n"
    "Your task: Implement the schedule bundle refactoring.\n\n"
    "Files to modify:\n"
    "- /Users/manczg/Documents/development/archon/install.py\n"
    "- /Users/manczg/Documents/development/archon/tests/test_installer_py.py\n\n"
    "Requirements:\n"
    "1. Move health_check.sh and qmd_checker.sh into the schedule bundle\n"
    "2. Update the installer to copy bundle scripts\n"
    "3. Ensure stale scripts are cleaned up on update\n"
    "Run: uv run pytest tests/test_installer_py.py -v to verify"
)

_REAL_TASK_DOCS = (
    "You are a documentation agent working in the Archon project at "
    "/Users/manczg/Documents/development/archon.\n\n"
    "Your task: Update Architecture documentation for the new feature.\n\n"
    "Files to update:\n"
    "- Documentation/Architecture/110_component_catalog_and_layer_breakdown.md\n"
    "- Documentation/Architecture/120_data_flow_and_message_lifecycle.md\n\n"
    "Describe the new PlanEvent bullet rendering behavior and update the output "
    "event table in the ADR. Include the n > 1 guard rationale."
)


def _make_realistic_plan(tasks: list[str], summary: str = "Multi-step research task") -> PlanEvent:
    agents = [AgentTask(id=f"a{i+1}", task=task) for i, task in enumerate(tasks)]
    plan = AgentPlan(scope="large", summary=summary, agents=agents)
    return PlanEvent(plan=plan, summary=summary)


# ── _task_summary helper tests ────────────────────────────────────────────────

def test_task_summary_short_text_unchanged() -> None:
    """Short single-line task text is returned as-is."""
    assert _task_summary("Research the codebase") == "Research the codebase"


def test_task_summary_truncates_at_100_chars() -> None:
    """Task text longer than 100 chars is truncated with ellipsis."""
    long = "A" * 110
    result = _task_summary(long)
    assert result.endswith("…")
    assert len(result) <= 101  # 100 chars + ellipsis char


def test_task_summary_takes_first_line_only() -> None:
    """Multi-paragraph task text: only the first line is shown."""
    multi = "Short first line\n\nLong second paragraph that goes on and on."
    assert _task_summary(multi) == "Short first line"


def test_task_summary_first_line_truncated_if_long() -> None:
    """First line exceeding 100 chars is still truncated."""
    long_first_line = "B" * 150 + "\n\nSecond paragraph."
    result = _task_summary(long_first_line)
    assert result.endswith("…")
    assert "Second paragraph" not in result


def test_task_summary_empty_string() -> None:
    """Empty string returns empty string."""
    assert _task_summary("") == ""


def test_task_summary_whitespace_only() -> None:
    """Whitespace-only string returns empty string after strip."""
    assert _task_summary("   ") == ""


def test_task_summary_exactly_100_chars() -> None:
    """String of exactly 100 chars is returned as-is (no ellipsis)."""
    exact = "C" * 100
    result = _task_summary(exact)
    assert result == exact
    assert not result.endswith("…")


def test_task_summary_exactly_101_chars() -> None:
    """String of exactly 101 chars is truncated."""
    over = "D" * 101
    result = _task_summary(over)
    assert result.endswith("…")
    assert len(result) == 101  # 100 chars + ellipsis


def test_task_summary_custom_max_len() -> None:
    """Custom max_len parameter is respected."""
    text = "Hello world, this is a long text"
    result = _task_summary(text, max_len=10)
    assert result.endswith("…")
    assert len(result) <= 11  # 10 + ellipsis


# ── Live integration tests with realistic decomposer output ──────────────────

def test_format_plan_event_realistic_research_tasks() -> None:
    """Multi-agent plan with realistic long task prompts shows truncated bullets.

    Validates that format_event produces a readable Telegram notification
    even when task text is a full agent prompt (hundreds of characters).
    """
    notif = NotificationsConfig(mode="normal")
    event = _make_realistic_plan(
        tasks=[_REAL_TASK_RESEARCH, _REAL_TASK_IMPLEMENT],
        summary="Deep research across Hungarian online retailers for Nike boots",
    )
    result = format_event(event, _split, notifications=notif)

    assert len(result) == 1
    msg = result[0]

    # Bullet markers present
    assert "• " in msg

    # Full prompts must not appear verbatim
    assert _REAL_TASK_RESEARCH not in msg
    assert _REAL_TASK_IMPLEMENT not in msg

    # Spawning line present
    assert "🔄 Spawning 2 agents..." in msg

    # Each bullet line is reasonably short (< 115 chars including bullet marker)
    for line in msg.split("\n"):
        if line.startswith("• "):
            assert len(line) <= 115, f"Bullet line too long ({len(line)} chars): {line!r}"


def test_format_plan_event_realistic_three_agents() -> None:
    """Three-agent plan with realistic prompts produces three bullets."""
    notif = NotificationsConfig(mode="normal")
    event = _make_realistic_plan(
        tasks=[_REAL_TASK_RESEARCH, _REAL_TASK_IMPLEMENT, _REAL_TASK_DOCS],
        summary="Research, implement, and document the new feature",
    )
    result = format_event(event, _split, notifications=notif)

    assert len(result) == 1
    msg = result[0]
    bullets = [line for line in msg.split("\n") if line.startswith("• ")]
    assert len(bullets) == 3
    assert "🔄 Spawning 3 agents..." in msg


def test_format_plan_event_realistic_bullet_content() -> None:
    """Bullet shows the truncated first line of the task, not the full prompt."""
    notif = NotificationsConfig(mode="normal")
    task_text = (
        "You are a web research agent. Your job is to find where to buy the "
        "Nike Zoom Mercurial Superfly 10 Academy FG/MG football boots in EU size 39 in Hungary online.\n\n"
        "Research these stores..."
    )
    event = _make_realistic_plan(
        tasks=[task_text, "Deploy results to the user"],
        summary="Find Nike boots in Hungary",
    )
    result = format_event(event, _split, notifications=notif)

    msg = result[0]
    # First bullet should contain the truncated first line
    assert "You are a web research agent" in msg
    # The second paragraph must not appear in the output
    assert "Research these stores" not in msg


def test_format_plan_event_message_fits_telegram_limit() -> None:
    """PlanEvent message with many agents stays within Telegram's 4096-char limit."""
    notif = NotificationsConfig(mode="normal")
    # Simulate 5 agents each with long task prompts
    long_tasks = [_REAL_TASK_RESEARCH] * 5
    event = _make_realistic_plan(
        tasks=long_tasks,
        summary="Parallel research across five store categories",
    )
    result = format_event(event, _split, notifications=notif)

    assert len(result) == 1
    assert len(result[0]) < 4096, f"Message exceeds Telegram limit: {len(result[0])} chars"


# ── Task 3.4: n > 1 guard assumption validation ──────────────────────────────

def test_task_3_4_single_agent_summary_self_descriptive() -> None:
    """Task 3.4: Validate the n > 1 guard assumption.

    For single-agent plans, the summary is used as the sole description (no bullets).
    This test uses real-world summary patterns from decomposer output to confirm
    that the summary is self-descriptive enough for a single-agent plan.

    Finding from live history inspection (2026-03-21):
    - Real summaries: "Deep research across Hungarian online retailers for Nike Zoom
      Mercurial Superfly 10 Academy FG/MG in EU size 39"
    - These are readable and informative on their own.
    - Single-agent plans are typically trivial/small tasks handled inline.
    - The n > 1 guard is VALID: single-agent plans don't need bullet lists.
    """
    notif = NotificationsConfig(mode="normal")
    summary = "Fix the installer update path regression for bundle scripts"
    task_text = (
        "You are a fix agent working at /Users/manczg/Documents/development/archon.\n"
        "Fix the installer update path regression. Read install.py and tests/test_installer_py.py first."
    )
    agents = [AgentTask(id="a1", task=task_text)]
    plan = AgentPlan(scope="large", summary=summary, agents=agents)
    event = PlanEvent(plan=plan, summary=summary)

    result = format_event(event, _split, notifications=notif)

    assert len(result) == 1
    msg = result[0]

    # No bullets for single agent
    assert "•" not in msg
    # Summary appears in message
    assert summary in msg
    assert "🔄 Spawning 1 agent..." in msg
    # The summary IS self-descriptive (readable human-friendly text)
    assert len(summary) > 10
    assert summary[0].isupper()  # starts with capital
